---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tailgrant
  annotations:
    item.homer.rajsingh.info/name: "TailGrant"
    item.homer.rajsingh.info/subtitle: "Temporary Access Grants"
    item.homer.rajsingh.info/logo: "https://pb.dashboardicons.com/api/files/community_gallery/syov2lst1k14n5m/favicon_kv7wixurym.svg"
    item.homer.rajsingh.info/keywords: "tailscale, access, grants, security"
    service.homer.rajsingh.info/name: "Infrastructure"
    service.homer.rajsingh.info/icon: "fas fa-shield-alt"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ts
      namespace: home
  hostnames:
    - "tailgrant.${CLUSTER_DOMAIN}"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: tailgrant
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
