---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailgrant
resources:
  - deployment-server.yaml
  - deployment-worker.yaml
  - service.yaml
  - httproute.yaml
  - rbac.yaml
  - secret.sops.yaml
  - pull-secret.yaml
  - pvc.yaml
configMapGenerator:
  - name: tailgrant-config
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
