---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailgrant-server-tsnet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block-replicated
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailgrant-worker-tsnet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block-replicated
  resources:
    requests:
      storage: 1Gi
