apiVersion: v1
kind: Secret
metadata:
    name: tailgrant-secrets
type: Opaque
stringData:
    TS_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:heR4w/KXBNx9nV2KcfSRYPI=,iv:YDoGs7taUD0zbxV1nm8YPuCd61H2am07jf2fmmW5OUo=,tag:t1ZQIsXYZgmwmibe9KFs5g==,type:str]
    TS_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:dReRb9B677KG0x8tQzu/8x9vquFewhKhOg8xSWM9tQ0JKjCJPIOL5seDoi6ISqdUuhxMiGqtfv0m5ZkhxtVf,iv:XlWSl+OKZHtW3w8tdccbo49oSdsPrd7gsLR7854lXdg=,tag:jc8weGVdlEKmasfbTW2VIQ==,type:str]
sops:
    lastmodified: "2026-02-13T07:14:52Z"
    mac: ENC[AES256_GCM,data:TKScCKGscqVyV35wJl+VlHoyoeCxH1jSuJZpa8R7sjsXvHjiITg79e7ffubHXek3VP/+sdCDsoJb0YDuvVNHjpToB7CSQamR6ycBl5iigXtdJO1faXk/7ncx1gjn3Ujh1JgVbXGqPWbyOzoLV0hMEvaeweJzHIhJHJyLfa4jIL0=,iv:CifgHOkQAKIIOMoDFYctQtqVLwlqs61Rt7Z+JJKTJy0=,tag:1fJdW1Ququ9fxKFBB0kJIA==,type:str]
    pgp:
        - created_at: "2026-02-13T07:14:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/+O6L5a90kD6WQ0cY5FwQphVnSMQZPAgO89CZxZBjmI0n7
            WOZwPCNggJKs0s74YjvZWF6F7sth6oXB+KZ4D+006Q1q98hOmdR8NukjwZKphATt
            I13dq8G2Z0TTGvL3ERVwfuVfvs64+mkvz/Kv2q/uGVxsaPMNLfEXLtXgOlxwSCGK
            mcZJfPHJT74tAILJViGgIDZplK1z9HyzLVy7WWJFk7+oLj9zm6WheOPJpsk4I1aG
            aJYtHGA00i0sw3i9vnqr4bzAOJe+6G4mXTrk/mDP+B5S6AbPAxCc7baXKa+ru/ET
            QdKlDb72BHiI7GJs36LpvBcDqvurSKyyLEPQdm4fx9elGehO+2HJTyOT1b+qVFQK
            odtsejpTXO9DmyJOuSoaGYmyFjMW/RTI/nXA988BtzCuJVSXlm3zbPSgo1mirELC
            c39mlmErTSZlzP6AfGTp7kW/vRuvH4EfEjeA/QxSeVgKbnAalpXJ+aUfJZ3h6Jfe
            FjlzySgrZO8iaAFfUJVPnMt4UHn4y1ThUvGIVh1l4k0ZR9IK8u5Wmp31l7powseh
            kvSPyXrNdTFpsqdyygGttg7bt09JLobbzZohbvj+v6MtPgARO6PxWTD+4UQjPjmz
            pmoK4pO4FXJLazn3BcjVU/G7kb8N/UusFfU3arKqhVF3XYDJCWs9Ku4y4lkA9ebU
            aAEJAhCK0hY+Jg8ALECaiI8FKKQyAJxf5Ubv+FtUUkGRFhRa5TIXpY+1UrbkGfAi
            KnTkei5g2Iz7l2Ype7LNLE0kHOo4DCPI4ik+iwtR3fJNnkeTGoM7lD+itr6+JHkk
            oZ/UQKMeHBrr
            =xp48
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
